### ISSUE TITLE
Support show full screen

### ISSUE THREAD

**Issue by enricobenedos** [SmallDreams/youtube_plyr_iframe#16]
Hello,

this library is helping us a lot on one of our projects. The is only a missing function that can really help and improve this library in our opinion `showFullScreen()`.

Is it possible to implement it?

Thanks

**Comment by jonatadashi** [comment]
Hi,
will need more information.
Are you asking if it should automatically go fullscreen or that there should be a separate button?

**Comment by enricobenedos** [comment]
We are looking for a way to start the player automatically on full screen. You can implement this function "simply" using a boolean like `startFullScreen: true` but in this way it is not very practical. 

A good idea in my opinion is to give to developers a clear function like `showFullScreen()`, in this way everyone is free to decide when player need to be showed on full screen.
