### ISSUE TITLE
Disable popup menu on long press

### ISSUE THREAD

**Issue by engineerdeep** [SmallDreams/youtube_plyr_iframe#22]
**Describe the bug**
Even after adding `IgnorePointer` on the iFrame, on tap it shows the pop up menu. Is there a way to disable it?

**To Reproduce:**
Add `IgnorePointer` widget on the player, and tap on it. 

**Expected behavior:**
Adding `IgnorePointer` widget on the player should not allow the pop up menu to be triggered.

**Screenshot**
<img width="380" alt="image" src="https://user-images.githubusercontent.com/38655985/116696816-702b1f80-a9d3-11eb-8edd-fea767afa011.png">

**Comment by schisms** [comment]
Second. IgnorePointer and Absorb act very weird with this plugin.

**Comment by jonatadashi** [comment]
This would make the whole iFrame unusable.

Workaround would be to use platform design instead.

I'll look into this, but as of now this is a low priority.

**Comment by tuanbs** [comment]
I had the same issue and see it's fixed in new version `2.0.6`. Thanks guys.

**Comment by hashirventhodi** [comment]
Please fix it .... this will makes the whole library unusable
