### ISSUE TITLE
The whole app crashes when YoutubePlayerIFrame widget is built on screen on iOS 14.5

### ISSUE THREAD

**Issue by oliatienza** [SmallDreams/youtube_plyr_iframe#23]
**Describe the bug**
The Flutter app crashes when `YoutubePlayerIFrame` widget is used

**To Reproduce:**
**On an iOS 14.5 device**
1. (In my case) Create a `ListView` widget
2. In one of the children of the `ListView`, have a `YoutubePlayerIFrame` instance

**Expected behavior:**
`YoutubePlayerIFrame` should load and display a Youtube player

**Flutter Doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version
    10.0.19042.928], locale en-PH)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)
```

**Additional context**
Observed on both an iPhone 11 Pro and iPhone 7 Plus. I can confirm that before updating to iOS 14.5, the same code works fine. No any special params passed onto the `YoutubePlayerIFrame` constructor

**Comment by ogdans3** [comment]
Probably the same as this issue: https://github.com/sarbagyastha/youtube_player_flutter/issues/487

I received the same complaint from apple (crashes on 14.5), unable to release the app to production.

**Comment by jonatadashi** [comment]
Hi,
it runs perfectly fine on my end. Can you post example code and flutter doctor -v

**Comment by oliatienza** [comment]
Hi, here's how I use it. May be something with the `gestureRecognizers` ?

```
...

 return YoutubePlayerIFrame(
      controller: controller,
      gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
    );

...
```

`flutter doctor -v`:
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.928], locale en-PH)
    • Flutter version 2.0.1 at C:\Development\flutter
    • Framework revision c5a4b4029c (9 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\oliat\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Development\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Development\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\oliat\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51

**Comment by jonatadashi** [comment]
Thanks, I'll have a look.

What I was expecting from flutter doctor was:
1. macOS version
2. Xcode version
Can you post that too and are you running sound null safety?

**Comment by jonatadashi** [comment]
Without further response this issue is getting closed and locked. Please open a new issue for related reports.
