### ISSUE TITLE
MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_1)

### ISSUE THREAD

**Issue by KatyTao** [SmallDreams/youtube_plyr_iframe#24]
Any help would be appreciated
**Describe the bug**
It runs perfectly on iOS devices, but on Android devices, it will throw an error `MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_1)` once dispose of the page, and the number increases every time the page is disposed. For example, if enter the page again and leave, it will display `No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_2`

**To Reproduce:**

- Use AVD (Android 11.0, API 30) to run the `example` in this github
- Enter the Inline demo page
- Click the back button to leave this page

**Error log**
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ ---------- ERROR ----------
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_1)
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ 
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ ------- STACK TRACE -------
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ <asynchronous suspension>
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ #1      InAppWebViewController.evaluateJavascript (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1375:16)
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ <asynchronous suspension>
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ 
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 8376): │ ⛔ ======================================================================
I/flutter ( 8376): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by jonatadashi** [comment]
Should be fixed. `youtube_plyr_iframe: ^2.0.5`

**Comment by KatyTao** [comment]
> Should be fixed. `youtube_plyr_iframe: ^2.0.5+1`

Thanks a lot :)

**Comment by 14103035sanyam** [comment]
@jonafeucht I am still facing this
I am using `youtube_plyr_iframe: ^2.0.7`
Can you please help here
