### ISSUE TITLE
How is this package different from youtube_player_iframe?

### ISSUE THREAD

**Issue by mvolpato** [SmallDreams/youtube_plyr_iframe#26]
The README says that it fixes some bugs. Is there a list of differences and maybe rationale why a new package has been created instead of contributing to the original one?

**Comment by jonatadashi** [comment]
I tried contributing to the main repo, I waited a few months for a successful merge before creating this fork.

Main differences:
- iOS actually works as described
- More frequent updates, quicker fixes and quality checks
- Additional methods

**Comment by mvolpato** [comment]
Thanks for the answer!
