### ISSUE TITLE
setVolume not working

### ISSUE THREAD

**Issue by schisms** [SmallDreams/youtube_plyr_iframe#30]
**Describe the bug**
setVolume not working 

**To Reproduce:**
Can be reproduced in example project by calling setVolume while a video is paused.

**Expected behavior:**
Video volume to change in response to setVolume

**Flutter Doctor:**
[✓] Flutter (Channel beta, 2.2.0-10.3.pre, on macOS 11.3.1 20E241 darwin-arm,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
[✓] Connected device (2 available)

**Additional context**
N/A

**Comment by jonatadashi** [comment]
Seems like to problems.

setVolume in general should be fixed.

Concerning setVolume on pause you'll have to set the state. See [volume_slider.dart](https://github.com/SmallDreams/youtube_plyr_iframe/blob/develop/example/lib/widgets/volume_slider.dart) for example.

**Comment by schisms** [comment]
Hi,

Thanks for the quick response.

I am having the same issue in the new example project you recently updated.

The problem arises within the inline demo. Volume_slider.dart line 40. The volume at 10 and 100 is the same. I even tried overriding the volume variable to 1. 1 and 100 are the same.

`ytController.setVolume(volume)`
Does not appear to do anything. Not in my project, nor example project.

Testing on iPhone 12 Pro Max Simulator. iOS 14.5.

Thanks again

**Comment by schisms** [comment]
Issue still persists

**Comment by schisms** [comment]
https://developers.google.com/youtube/v3/guides/ios_youtube_helper

> Most of the IFrame Player API functions have Objective-C equivalents, though some of the naming may differ slightly to more closely match Objective-C coding guidelines. Notable exceptions are methods controlling the volume of the video, since these are controlled by the phone hardware or with built in UIView instances designed for this purpose, such as MPVolumeView.

Doesn't look like its possible.

Great plugin nonetheless.
