### ISSUE TITLE
When rotating device, youtubeplayer widget is rebuilding

### ISSUE THREAD

**Issue by Katekko** [SmallDreams/youtube_plyr_iframe#34]
Describe the bug
When rotating device, youtubeplayer widget is rebuilding

To Reproduce
open player screen and than rotate phone to change orientation

Expected behavior
widget state should be maintained

**Comment by jonafeucht** [comment]
This is pretty unspecific. What device or rather OS are you encountering this? Are you using platform design or not?

**Comment by Katekko** [comment]
> This is pretty unspecific. What device or rather OS are you encountering this? Are you using platform design or not?

Platform: android or web
I create a simple project to test this and when you resize the screen(web) or rotate the device (app) the widget rebuilds and the video's state is lost. The video need to maintain the state after rebuild the widget.

What you mean when you say platform design?

**Comment by jonafeucht** [comment]
Hi, sorry can't reproduce this.

My best guess is that you're device is having not enough memory, thus resulting in a complete rebuild to cope with the sudden device rotation.

What device are you testing this on?

**Comment by Katekko** [comment]
Morning, I'v made a project for you.
https://github.com/Katekko/test_youtube

Just run for web, start the video and resize the page, your video will restart.

----

Another question, the lib has any feature to remove the related videos from the player?

**Comment by Katekko** [comment]
@jonafeucht any news?

**Comment by Katekko** [comment]
> You can hide almost everything when using `YoutubePlayerController` (see [methods](https://github.com/SmallDreams/youtube_plyr_iframe#available-methods)). This only works when desktopmode is false and won't work on web.
> 
> As for the resizing, still can't reproduce. Neither on Windows, Linux or macOS.

Did you use my example project? 

I will make a video for yout

**Comment by jonafeucht** [comment]
Yeah, that be great.
