### ISSUE TITLE
The buffered value always returns 1 when playing forward/backward.

### ISSUE THREAD

**Issue by tuanbs** [SmallDreams/youtube_plyr_iframe#35]
When I play forward/backward or drag/seek the video, the buffered value always returns 1. The expected value is the current video position. For example, when the video position is at time 00:15, we press the forward button and now video position is at 00:30, then the expected result should be `30`:
```dart
YoutubePlayerController _controller = YoutubePlayerController(
    initialVideoId: 'K18cpp_-gP8',
    params: YoutubePlayerParams(
        startAt: Duration(seconds: 10),
        showControls: true,
        showFullscreenButton: true,
    ),
)..listen((value) {
    if (value.playerState == PlayerState.buffering) {
        print('bufferedTime is: ${value.buffered.seconds.inSeconds}'); // Always 1.
    }
});
```

Any idea or workaround? Thanks in advance and please keep evolving this plugin as I see it solves many issues exists in `youtube_player_iframe`.

**Comment by jonafeucht** [comment]
Hi,

This is how I would approach it.
```dart
if (value.playerState == PlayerState.buffering) {
          String _time(Duration duration) {
            return "${duration.inMinutes}:${duration.inSeconds}";
          }

          Future.delayed(Duration(milliseconds: 500), () {
            final bufferedTime = _controller.value.position;
            return print("${_time(bufferedTime)}");
          });
        }
```

Why the delay?
If there is no delay, it will get the last known position, instead of the future or rather current position.

**Comment by tuanbs** [comment]
> Hi,
> 
> This is how I would approach it:
> 
> ```dart
> if (value.playerState == PlayerState.buffering) {
>           String _time(Duration duration) {
>             return "${duration.inMinutes}:${duration.inSeconds}";
>           }
> 
>           Future.delayed(Duration(milliseconds: 500), () {
>             final bufferedTime = value.position;
>             return print("${_time(bufferedTime)}");
>           });
>         }
> ```
> 
> Why the delay?
> If there is no delay, it will get the last known position, instead of the future or rather current position.

@jonafeucht Well, I tried this approach and see the bufferedTime is not correct. It returns the time when it starts playing forward/backward, not the time of the current position.
