### ISSUE TITLE
Full screen Button on flutter web is not working.

### ISSUE THREAD

**Issue by jaikrishnachandrasekar** [SmallDreams/youtube_plyr_iframe#36]
When i use this link https://smalldreams.github.io/Web-Example/#/ from pub dev site, full screen button was working fine.

Same Sample when was in the https://github.com/SmallDreams/youtube_plyr_iframe in local, the full screen button is not working. 

The issue occured when i tried your package on our project.

Running this Sample https://github.com/SmallDreams/youtube_plyr_iframe, itself reproduces the issue.(Flutter web)

Do i need to configure any other thing from the package.

**Comment by jonafeucht** [comment]
Seems like the last flutter version broke something.

A workaround is to build and release in the html renderer.
https://github.com/SmallDreams/youtube_plyr_iframe/blob/develop/README.md#web

**Comment by jaikrishnachandrasekar** [comment]
I think it was fixed in the latest flutter upgrade today, but when we resize the browser window, it is getting weird ui, the console window is showing the error below :

Height of Platform View type: [youtube-player-1063275035] may not be set. Defaulting to height: 100%.
Set style.height to any appropriate value to stop this message.
Width of Platform View type: [youtube-player-1063275035] may not be set. Defaulting to width: 100%.
Set style.width to any appropriate value to stop this message.

**Comment by jaikrishnachandrasekar** [comment]
Thanks for the response, when shall we find the release for the fix?

**Comment by jonafeucht** [comment]
For now I've only released a pre release which should fix the error message you're getting, but not the weird ui on resizing.
`youtube_plyr_iframe: ^2.0.7-pre.1`

**Comment by jaikrishnachandrasekar** [comment]
Are you able to reproduce the issue or do i need to share any sample code to reproduce the issue?

**Comment by jaikrishnachandrasekar** [comment]
Closing this issue as the full screen issue was fixed in the flutter latest version and choppiness on the UI is from the flutter and i have opened an issue in flutter - https://github.com/flutter/flutter/issues/85522
